import React from 'react'
import {Link} from 'react-router-dom'
import "../style.css"
import "./Post.css"

const img1 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135835650_1179784109118381_3203309990222587651_o.jpg?_nc_cat=108&ccb=2&_nc_sid=730e14&_nc_ohc=5ip823gowBkAX8xweCt&_nc_ht=scontent-del1-1.xx&oh=2e7660404b9d744701a1d3505cc9d1be&oe=601E9A60"

const img2 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/136440880_1179784209118371_830000982361869958_o.jpg?_nc_cat=107&ccb=2&_nc_sid=730e14&_nc_ohc=g9BmJZiWBqcAX9ozQNv&_nc_ht=scontent-del1-1.xx&oh=7aaa7d61e43fef90a786ae363145a13a&oe=601E5088"

const img3 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135754983_1179784165785042_2666235542754388444_o.jpg?_nc_cat=106&ccb=2&_nc_sid=730e14&_nc_ohc=nXRO62wHU5UAX-Pa3vj&_nc_ht=scontent-del1-1.xx&oh=249142926c3dab8e4ba23535cf0c6337&oe=601F4E32"

const img4 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/137044159_1179784099118382_3665349281209607889_o.jpg?_nc_cat=107&ccb=2&_nc_sid=730e14&_nc_ohc=nb--jnGiM20AX9fs1Vq&_nc_ht=scontent-del1-1.xx&oh=3e5ee41785691d43e39bcf6dd97b55c2&oe=601D568C"

const img5 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135536392_1179784102451715_4290369423892379573_o.jpg?_nc_cat=110&ccb=2&_nc_sid=730e14&_nc_ohc=wgz4AteEonwAX8nv2hY&_nc_ht=scontent-del1-1.xx&oh=ab41f19ec91a1e9434a05c6219c691f7&oe=601D80B0"

const img6 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135539551_1179784179118374_1157000678050998101_o.jpg?_nc_cat=108&ccb=2&_nc_sid=730e14&_nc_ohc=E8gGw6tGLDIAX_1drJs&_nc_ht=scontent-del1-1.xx&oh=e5737c0c3b14e13b2aa25020af6583c8&oe=601E4C0F"

const img7 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/136462542_1179784155785043_5344573109352192750_o.jpg?_nc_cat=102&ccb=2&_nc_sid=730e14&_nc_ohc=J7UerNUqPHcAX_vJZ_T&_nc_ht=scontent-del1-1.xx&oh=3e6fbfd418c3519060bc19e8265ba100&oe=601EBCEA"

const Post2 = () => {
  return (
    <div>
          <div class="nav-wrapper">

                <Link to="/">
                      <div class="dots-wrapper">
                            <div id="dot-1" class="browser-dot"></div>
                            <div id="dot-2" class="browser-dot"></div>
                            <div id="dot-3" class="browser-dot"></div>
                      </div>
                </Link>

                <ul id="navigation">
                  <li><Link to="/#contactt">Contact</Link></li>

                </ul>
          </div>

          <div class="main-container">
                <br/>

                <div class="img-container">
                  <img src={img1} alt="pic"/>
                </div>

                <h3>Hotel Booking System</h3>

                <p>This was one of the  project I created with React-Js. I was the sole creator/developer for the project .
                <br/><br/>
                This project was a hotel booking app and have all the functionality that a real hotel wants to have including log-in, sign-up, all types of filter, Recommandations of the hotels on the basis of filters.
                <br/><br/>
                Cost filter, Room filter and booking the hotels were also some of the Functionalities.
                search results would be generated by fetching the API's . User can see all the hotels listed and all the discription about the hotel .
                <br/><br/>
                Customers had the ability to view all their data with a dynamic search form, and would get email after placing a booking
                <br/><br/>
                I worked on this system for 2 weeks as my frontend React-Js project, one of my most favourite library to work on is React-Js</p>

                <h5>Technologies:</h5>

                <ul>
                      <li>- React JS</li>
                      <li>- Hotel Api</li>
                      <li>- Json-sever (Local Api)</li>
                      <li>- JWT Log-in & Sign-up</li>
                      <li>- BootStrap</li>
                      <li>- Material-Ui</li>
                      <li>- Google Maps API</li>
                      <li>- Google Fonts</li>
                </ul>

                <h5>Login Dashboard</h5>
                <div class="img-container">
                  <img src={img2} alt="pic"/>
                </div>

                <h5>Sample Signup Form</h5>
                <div class="img-container">
                  <img src={img3} alt="pic"/>
                </div>

                <h5>Recommandations on the basis of trip type</h5>
                <div class="img-container">
                  <img src={img4} alt="pic"/>
                </div>

                <h5>Filter Results (Cost and Room type)</h5>
                <div class="img-container">
                  <img src={img5} alt="pic"/>
                </div>

                <h5>Hotel Details Page</h5>
                <div class="img-container">
                  <img src={img6} alt="pic"/>
                </div>

                <h5>Booking Page</h5>
                <div class="img-container">
                  <img src={img7} alt="pic"/>
                </div>
          </div>
    </div>
    )
}

export default Post2
