import React from 'react'
import {Link} from 'react-router-dom'
import "../style.css"
import "./Post.css"

const img1 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135839271_1179744149122377_5912920449128970734_o.jpg?_nc_cat=109&ccb=2&_nc_sid=730e14&_nc_ohc=kLUFk2lKbP4AX9gOzwr&_nc_ht=scontent-del1-1.xx&oh=c8900b896508c846097b4088e364d21d&oe=6020A64B"

const img2 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/136189895_1179744105789048_4989233509269354540_o.jpg?_nc_cat=107&ccb=2&_nc_sid=730e14&_nc_ohc=KUflgaUG0DwAX_lyuz5&_nc_ht=scontent-del1-1.xx&oh=674ec09a5ec5d19871dda3bc0eb94104&oe=601EF537"

const img3 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135824816_1179744095789049_132672073451638485_o.jpg?_nc_cat=108&ccb=2&_nc_sid=730e14&_nc_ohc=Siq8HBjEMUkAX-LW35j&_nc_ht=scontent-del1-1.xx&oh=3c09c7892d2c935fb477e5fd93b6237d&oe=601F9DBC"

const img4 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135687193_1179744115789047_1801896923135885756_o.jpg?_nc_cat=106&ccb=2&_nc_sid=730e14&_nc_ohc=a4uytYo8tGQAX_JWpGy&_nc_ht=scontent-del1-1.xx&oh=98c1c7c1055a4eeb8f668309eeeb5086&oe=60209636"

const img5 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135524705_1179744142455711_7956963143146596982_o.jpg?_nc_cat=104&ccb=2&_nc_sid=730e14&_nc_ohc=TBO1fhu6gQIAX8ShZJu&_nc_ht=scontent-del1-1.xx&oh=70f5915ffa109164e1a6c5c3c4077060&oe=60202329"

const img6 = "https://scontent-del1-1.xx.fbcdn.net/v/t1.0-9/135590102_1179744132455712_8833041546914233793_o.jpg?_nc_cat=102&cb=846ca55b-311e05c7&ccb=2&_nc_sid=730e14&_nc_ohc=q17HnwLtaksAX8ECFKi&_nc_ht=scontent-del1-1.xx&oh=240287e34764df8a4e8937712d8c151b&oe=601D892E"

const Post1 = () => {
  return (
    <div>
          <div class="nav-wrapper">

                <Link to="/">
                      <div class="dots-wrapper">
                            <div id="dot-1" class="browser-dot"></div>
                            <div id="dot-2" class="browser-dot"></div>
                            <div id="dot-3" class="browser-dot"></div>
                      </div>
                </Link>

                <ul id="navigation">
                  <li><Link to="/#contactt">Contact</Link></li>

                </ul>
          </div>

          <div class="main-container">
                <br/>

                <div class="img-container">
                  <img src={img1} alt="pic"/>
                </div>

                <h3>Food Delivery App</h3>

                <p>This was a project I started as my very first frontend project when I first learned HTML, CSS AND JavaScript. I was the sole creator/developer for the of the project.
                <br/><br/>
                The system stored sample data for the restraunts search and provided all the data about a particular restraunt  and admins to view, add and send data to clients.
                <br/><br/>
                search results would be generated by the fetching the data from the API  and the sytem had location based filters and category based filters interface for customers to be able to login and view.
                <br/><br/>
                Customers had the ability to view all their data with a dynamic search form, trend data.
                <br/><br/>
                I completed this project within 24hours of time , and i was really happy after completing my very first project.</p>

                <h5>Technologies:</h5>

                <ul>
                      <li>- HTML</li>
                      <li>- CSS</li>
                      <li>- JavaScript</li>
                      <li>- BootStrap</li>
                      <li>- Font Awesome Icons</li>
                      <li>- Hotel Api</li>
                      <li>- Google Fonts</li>
                </ul>

                <h5>Restaurants on the basis of Types</h5>
                <div class="img-container">
                  <img src={img2} alt="pic"/>
                </div>

                <h5>APP Store</h5>
                <div class="img-container">
                  <img src={img3} alt="pic"/>
                </div>

                <h5>All Locations</h5>
                <div class="img-container">
                  <img src={img4} alt="pic"/>
                </div>

                <h5>About Page</h5>
                <div class="img-container">
                  <img src={img5} alt="pic"/>
                </div>

                <h5>Vision Page</h5>
                <div class="img-container">
                  <img src={img6} alt="pic"/>
                </div>
          </div>
    </div>
    )
}

export default Post1
